---
title: "Total 1_6"
author: "TRAN Thi Hong Nhung"
date: '2024-05-31'
output: 
  word_document:
    reference_docx: StylesPourWord.docx
---


```{r,echo=FALSE,warning=FALSE,message=FALSE}
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(GGally))
suppressPackageStartupMessages(library(dplyr))
```
```{r}
data <- read.csv("bilan0.csv", sep = ";")
list_emet_period <- unique(data$nom)
print(list_emet_period)


# Analyser pour chaque période et chaque émetteur
for (nom_emet in list_emet_period) {
  # Combine data from all periods
  data_period1 <- read.csv(paste("period_1_", nom_emet, ".csv", sep = ""), sep = ";")
  data_period1$Periode <- "Période 1"
  
  data_period2 <- read.csv(paste("period_2_", nom_emet, ".csv", sep = ""), sep = ";")
  data_period2$Periode <- "Période 2"
  
  data_period3 <- read.csv(paste("period_3_", nom_emet, ".csv", sep = ""), sep = ";")
  data_period3$Periode <- "Période 3"
  data_period3$B <- as.numeric(data_period3$B)
  data_period3$CONVERSION_TYPE <- as.integer(data_period3$CONVERSION_TYPE)
  data_period3$EARTH_AZIMUTH_ANGLE <- as.numeric(data_period3$EARTH_AZIMUTH_ANGLE)
  
  data_combine <- bind_rows(data_period1, data_period2, data_period3)
  data_combine$TIME <- as.Date(data_combine$TIME)
  print(ggplot(data_combine, aes(x = Periode, y = ENERGY, color = Periode)) +
    geom_boxplot(fill = "pink") +
    labs(x = "Temps", y = "Energy (MEV)", title = paste("L'énergie de", nom_emet, "sur trois périodes")) +
    theme_classic()+
    theme(plot.title = element_text(hjust = 0.5, size =10)))
  data_combine_filtre <- data_combine[data_combine$ENERGY <= 1500,]
  print(ggplot(data_combine_filtre, aes(x = Periode, y = ENERGY, color = Periode)) +
    geom_boxplot(fill = "pink") +
    labs(x = "Temps", y = "Energy (MEV)", title = paste("L'énergie de", nom_emet, "sur trois périodes")) +
    theme_classic()+
    theme(plot.title = element_text(hjust = 0.5, size =10)))
  
  print(ggplot(data_combine_filtre, aes(x = ENERGY)) +
    geom_histogram(fill = "pink", color = "black", bins = 20) +
    labs(x = "Énergie (MEV)", y = "Fréquence", title = paste("Répartition de l'énergie de", nom_emet, "sur 3 périodes")) +
    theme_classic()+
    theme(plot.title = element_text(hjust = 0.5, size =10)))
  
  # Intervalle de confiance pour chaque émetteur
  data_emet <- data[data$nom == nom_emet,]
  print(paste("Les statistiques de",nom_emet,":"))
  print(select(data_emet, 17,2,5,6,12,13,14,15))
  print(ggplot(data_emet, aes(annee, moyenne, ymin = borne_inf, ymax = borne_sup)) +
    geom_errorbar(color = "blue", width = 0.4) +
    geom_point(size = 2, color = "red") +
    geom_line(color = "red") +
    labs(x = "Temps", y = "Énergie", title = paste("IC de la moyenne d'énergie de", nom_emet, "par temps")) +
    scale_x_continuous(breaks = seq(2007, 2018, by = 1)) +
    scale_y_continuous(breaks = seq(0, 2000, by = 20)) +
    theme_bw())+
    theme(plot.title = element_text(hjust = 0.5, size =10)) 
  
  # Intervalle de confiance pour chaque tranche d'énergie
  for (energy_range in c(500, 1000)) {
  energy_start <- (energy_range - 500)
  data_range <- read.csv(paste("bilan", energy_range, ".csv", sep = ""), sep = ";")
  data_range <- data_range[data_range$nom == nom_emet,]
  print(paste("Les statistiques de", nom_emet, "[",energy_start,":", energy_range, "]meV :"))
  print(select(data_range, 17, 2, 5, 6, 12, 13, 14, 15))
  print(
    ggplot(data_range, aes(annee, moyenne, ymin = borne_inf, ymax = borne_sup)) +
      geom_errorbar(color = "blue", width = 0.4) +
      geom_point(size = 2, color = "red") +
      geom_line(color = "red") +
      labs(
        x = "Temps", y = "Énergie",
        title = paste("IC de la moyenne d'énergie de", nom_emet, "par temps,", paste("[", energy_start, ":", energy_range, "]meV"))
      ) +
      theme(plot.title = element_text(hjust = 0.5)) +
      scale_x_continuous(breaks = seq(2007, 2018, by = 1)) +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5, size =10)) )}
}

```

